package com.mudassir.ytdownloader

import android.os.Build
import kotlinx.coroutines.Dispatchers
import kotlinx.coroutines.async
import kotlinx.coroutines.awaitAll
import kotlinx.coroutines.runBlocking
import okhttp3.OkHttpClient
import okhttp3.Request
import org.schabi.newpipe.extractor.Image
import org.schabi.newpipe.extractor.MediaFormat
import org.schabi.newpipe.extractor.Page
import org.schabi.newpipe.extractor.ServiceList
import org.schabi.newpipe.extractor.StreamingService.LinkType
import org.schabi.newpipe.extractor.channel.ChannelInfo
import org.schabi.newpipe.extractor.channel.tabs.ChannelTabInfo
import org.schabi.newpipe.extractor.channel.tabs.ChannelTabs
import org.schabi.newpipe.extractor.playlist.PlaylistInfo
import org.schabi.newpipe.extractor.search.SearchInfo
import org.schabi.newpipe.extractor.services.youtube.linkHandler.YoutubeSearchQueryHandlerFactory
import org.schabi.newpipe.extractor.stream.AudioStream
import org.schabi.newpipe.extractor.stream.AudioTrackType
import org.schabi.newpipe.extractor.stream.DeliveryMethod
import org.schabi.newpipe.extractor.stream.Stream
import org.schabi.newpipe.extractor.stream.StreamInfo
import org.schabi.newpipe.extractor.stream.StreamInfoItem
import org.schabi.newpipe.extractor.stream.VideoStream
import java.util.concurrent.TimeUnit

/** MERGE = separate video + audio tracks merged on the phone. */
enum class Kind { MERGE, SINGLE_VIDEO, AUDIO }

/** One downloadable choice. */
data class DownloadOption(
    val kind: Kind,
    val height: Int,
    val label: String,
    val videoUrl: String?,
    val audioUrl: String?,
    val videoItag: Int,
    val audioItag: Int,
    /** "mp4", "webm" or "m4a". */
    val extension: String,
    val bytes: Long // -1 if unknown
) {
    val displayLabel: String
        get() = if (bytes > 0) "$label · ${formatBytes(bytes)}" else label
    val mime: String
        get() = when (extension) {
            "m4a" -> "audio/mp4"
            "webm" -> "video/webm"
            else -> "video/$extension"
        }
}

data class SubtitleTrack(val url: String, val language: String, val autoGenerated: Boolean)

data class VideoDetails(
    val id: String,
    val title: String,
    val uploader: String,
    val durationSec: Long,
    val thumbnail: String?,
    val options: List<DownloadOption>,
    val subtitles: List<SubtitleTrack>
)

/** A video in a playlist, channel or search result. */
data class VideoEntry(
    val id: String,
    val url: String,
    val title: String,
    val uploader: String,
    val durationSec: Long,
    val thumbnail: String?
)

data class VideoList(val name: String, val url: String, val isChannel: Boolean, val videos: List<VideoEntry>)

data class SearchPage(val query: String, val videos: List<VideoEntry>, val next: Page?)

object YouTube {

    private val service get() = ServiceList.YouTube
    private val headClient = OkHttpClient.Builder().callTimeout(10, TimeUnit.SECONDS).build()

    enum class Link { VIDEO, PLAYLIST, CHANNEL, NONE }

    fun linkType(url: String): Link = try {
        when (service.getLinkTypeByUrl(url)) {
            LinkType.STREAM -> Link.VIDEO
            LinkType.PLAYLIST -> Link.PLAYLIST
            LinkType.CHANNEL -> Link.CHANNEL
            else -> Link.NONE
        }
    } catch (e: Exception) {
        Link.NONE
    }

    /** The playlist link inside a "watch?v=…&list=…" URL, if any. */
    fun playlistOf(url: String): String? =
        Regex("[?&]list=([\\w-]+)").find(url)?.groupValues?.get(1)
            ?.takeUnless { it.startsWith("RD") } // "Mix" radio lists can't be opened as playlists
            ?.let { "https://www.youtube.com/playlist?list=$it" }

    fun videoId(url: String): String =
        Regex("(?:v=|youtu\\.be/|shorts/|embed/|live/)([\\w-]{11})").find(url)?.groupValues?.get(1) ?: url

    /** WebM (VP9 + Opus) merging needs Android 10+ for reliable Opus support in MediaMuxer. */
    val webmSupported get() = Build.VERSION.SDK_INT >= Build.VERSION_CODES.Q

    fun getVideo(url: String, allowWebm: Boolean = true): VideoDetails {
        val info = StreamInfo.getInfo(service, url)

        // Only the original audio language (skip dubbed tracks).
        fun AudioStream.original() = audioTrackType == null || audioTrackType == AudioTrackType.ORIGINAL

        val m4aAudio = info.audioStreams
            .filter { it.usable() && it.original() && it.format == MediaFormat.M4A }
            .sortedByDescending { it.averageBitrate }
        val opusAudio = info.audioStreams
            .filter {
                it.usable() && it.original() &&
                    (it.format == MediaFormat.WEBMA_OPUS || it.format == MediaFormat.WEBMA) &&
                    (it.codec ?: "opus").contains("opus")
            }
            .maxByOrNull { it.averageBitrate }
        val bestM4a = m4aAudio.firstOrNull()

        val options = mutableListOf<DownloadOption>()

        // HD MP4: H.264 video-only tracks (YouTube offers these up to 1080p), best bitrate per height.
        if (bestM4a != null) {
            info.videoOnlyStreams
                .filter { it.usable() && it.format == MediaFormat.MPEG_4 && (it.codec ?: "avc1").startsWith("avc1") }
                .groupBy { it.height }
                .mapNotNull { (_, list) -> list.maxByOrNull { it.bitrate } }
                .forEach { v -> options += merged(v, bestM4a, "mp4", "MP4") }
        }

        // 1440p / 4K: only exist as VP9 WebM. Merged with Opus audio into a .webm file.
        if (allowWebm && webmSupported && opusAudio != null) {
            val maxMp4 = options.maxOfOrNull { it.height } ?: 0
            info.videoOnlyStreams
                .filter {
                    it.usable() && it.format == MediaFormat.WEBM &&
                        (it.codec ?: "vp9").let { c -> c.startsWith("vp9") || c.startsWith("vp09") } &&
                        it.height > maxMp4
                }
                .groupBy { it.height }
                .mapNotNull { (_, list) -> list.maxByOrNull { it.bitrate } }
                .forEach { v -> options += merged(v, opusAudio, "webm", "WebM") }
        }

        // Fallback: single-file video+audio (usually 360p only).
        info.videoStreams
            .filter { it.usable() }
            .filter { v -> options.none { it.height == v.height } }
            .forEach { v ->
                val ext = v.format?.suffix ?: "mp4"
                options += DownloadOption(
                    kind = Kind.SINGLE_VIDEO, height = v.height,
                    label = "${v.resolution} · ${ext.uppercase()}",
                    videoUrl = v.content, audioUrl = null,
                    videoItag = v.itag, audioItag = -1,
                    extension = ext, bytes = sizeOf(v)
                )
            }

        options.sortByDescending { it.height }

        // Audio only (M4A, works in every player).
        m4aAudio.distinctBy { it.averageBitrate }.take(2).forEach { a ->
            options += DownloadOption(
                kind = Kind.AUDIO, height = 0,
                label = "Audio only ${a.averageBitrate} kbps · M4A",
                videoUrl = null, audioUrl = a.content,
                videoItag = -1, audioItag = a.itag,
                extension = "m4a", bytes = sizeOf(a)
            )
        }

        fillMissingSizes(options)

        val subs = info.subtitles
            .filter { it.isUrl && it.format == MediaFormat.VTT }
            .map { SubtitleTrack(it.content, it.languageTag, it.isAutoGenerated) }

        return VideoDetails(
            id = videoId(url),
            title = info.name,
            uploader = info.uploaderName ?: "",
            durationSec = info.duration,
            thumbnail = bestThumb(info.thumbnails),
            options = options,
            subtitles = subs
        )
    }

    private fun merged(v: VideoStream, a: AudioStream, ext: String, name: String): DownloadOption {
        val vb = sizeOf(v)
        val ab = sizeOf(a)
        return DownloadOption(
            kind = Kind.MERGE, height = v.height,
            label = "${v.resolution} · $name",
            videoUrl = v.content, audioUrl = a.content,
            videoItag = v.itag, audioItag = a.itag,
            extension = ext,
            bytes = if (vb > 0 && ab > 0) vb + ab else -1
        )
    }

    /**
     * Best option at or below [maxHeight]; maxHeight == 0 means audio only.
     * If [videoItag]/[audioItag] are given and still offered, that exact format is reused
     * so a partially downloaded file can be resumed.
     */
    fun pickBest(options: List<DownloadOption>, maxHeight: Int, videoItag: Int = -1, audioItag: Int = -1): DownloadOption? {
        if (videoItag != -1 || audioItag != -1) {
            options.firstOrNull { it.videoItag == videoItag && it.audioItag == audioItag }?.let { return it }
        }
        return if (maxHeight == 0) options.firstOrNull { it.kind == Kind.AUDIO }
        else options.filter { it.kind != Kind.AUDIO && it.height <= maxHeight }.maxByOrNull { it.height }
            ?: options.filter { it.kind != Kind.AUDIO }.minByOrNull { it.height }
    }

    /** Subtitle track for [lang] (e.g. "en"), preferring human-written over auto-generated. */
    fun pickSubtitle(subs: List<SubtitleTrack>, lang: String): SubtitleTrack? {
        if (lang.isBlank()) return null
        val matching = subs.filter { it.language.equals(lang, true) || it.language.startsWith("$lang-", true) }
        return matching.firstOrNull { !it.autoGenerated } ?: matching.firstOrNull()
    }

    fun getPlaylist(url: String, onProgress: (Int) -> Unit = {}): VideoList {
        val info = PlaylistInfo.getInfo(service, url)
        val items = info.relatedItems.toMutableList()
        onProgress(items.size)
        var next: Page? = info.nextPage
        while (Page.isValid(next)) {
            val more = PlaylistInfo.getMoreItems(service, url, next)
            items += more.items
            onProgress(items.size)
            next = more.nextPage
        }
        return VideoList(info.name, url, isChannel = false, videos = items.map { it.toEntry() })
    }

    /** The newest [limit] uploads of a channel. */
    fun getChannel(url: String, limit: Int, onProgress: (Int) -> Unit = {}): VideoList {
        val info = ChannelInfo.getInfo(service, url)
        val tab = info.tabs.firstOrNull { it.contentFilters.contains(ChannelTabs.VIDEOS) }
            ?: throw IllegalStateException("This channel has no videos tab")
        val tabInfo = ChannelTabInfo.getInfo(service, tab)
        val items = tabInfo.relatedItems.filterIsInstance<StreamInfoItem>().toMutableList()
        onProgress(items.size)
        var next: Page? = tabInfo.nextPage
        while (items.size < limit && Page.isValid(next)) {
            val more = ChannelTabInfo.getMoreItems(service, tab, next!!)
            items += more.items.filterIsInstance<StreamInfoItem>()
            onProgress(items.size)
            next = more.nextPage
        }
        return VideoList(info.name, url, isChannel = true, videos = items.take(limit).map { it.toEntry() })
    }

    fun search(query: String): SearchPage {
        val handler = service.searchQHFactory.fromQuery(query, listOf(YoutubeSearchQueryHandlerFactory.VIDEOS), "")
        val info = SearchInfo.getInfo(service, handler)
        return SearchPage(query, info.relatedItems.filterIsInstance<StreamInfoItem>().map { it.toEntry() }, info.nextPage)
    }

    fun searchMore(page: SearchPage): SearchPage {
        val next = page.next ?: return page.copy(next = null)
        val handler = service.searchQHFactory.fromQuery(page.query, listOf(YoutubeSearchQueryHandlerFactory.VIDEOS), "")
        val more = SearchInfo.getMoreItems(service, handler, next)
        return SearchPage(
            page.query,
            page.videos + more.items.filterIsInstance<StreamInfoItem>().map { it.toEntry() },
            more.nextPage?.takeIf { Page.isValid(it) }
        )
    }

    // --- helpers ---

    private fun StreamInfoItem.toEntry() = VideoEntry(
        id = videoId(url), url = url, title = name,
        uploader = uploaderName ?: "", durationSec = duration,
        thumbnail = bestThumb(thumbnails)
    )

    /** A thumbnail around 360–480px high: sharp in lists without being huge. */
    fun bestThumb(images: List<Image>): String? =
        images.filter { it.height in 1..480 }.maxByOrNull { it.height }?.url
            ?: images.firstOrNull()?.url

    private fun Stream.usable() = deliveryMethod == DeliveryMethod.PROGRESSIVE_HTTP && isUrl

    /** Size from YouTube's metadata or the "clen" URL parameter, without any network call. */
    private fun sizeOf(s: Stream): Long {
        val fromItag = s.itagItem?.contentLength ?: -1L
        if (fromItag > 0) return fromItag
        return Regex("[?&]clen=(\\d+)").find(s.content)?.groupValues?.get(1)?.toLongOrNull() ?: -1L
    }

    /** For anything still unknown, ask the server (HEAD) in parallel. */
    private fun fillMissingSizes(options: MutableList<DownloadOption>) {
        if (options.none { it.bytes <= 0 }) return
        runBlocking(Dispatchers.IO) {
            val filled = options.map { o ->
                async {
                    if (o.bytes > 0) o
                    else {
                        val v = o.videoUrl?.let { head(it) } ?: 0L
                        val a = o.audioUrl?.let { head(it) } ?: 0L
                        val ok = (o.videoUrl == null || v > 0) && (o.audioUrl == null || a > 0)
                        o.copy(bytes = if (ok) v + a else -1)
                    }
                }
            }.awaitAll()
            options.clear()
            options.addAll(filled)
        }
    }

    private fun head(url: String): Long = try {
        headClient.newCall(
            Request.Builder().url(url).head().header("User-Agent", OkHttpDownloader.USER_AGENT).build()
        ).execute().use { it.header("Content-Length")?.toLongOrNull() ?: -1L }
    } catch (e: Exception) {
        -1L
    }
}

fun formatBytes(bytes: Long): String = when {
    bytes < 0 -> "?"
    bytes >= 1L shl 30 -> "%.2f GB".format(bytes / (1L shl 30).toDouble())
    bytes >= 1L shl 20 -> "%.1f MB".format(bytes / (1L shl 20).toDouble())
    else -> "%.0f KB".format(bytes / 1024.0)
}

fun formatDuration(sec: Long): String {
    if (sec < 0) return ""
    val h = sec / 3600
    val m = (sec % 3600) / 60
    val s = sec % 60
    return if (h > 0) "%d:%02d:%02d".format(h, m, s) else "%d:%02d".format(m, s)
}
